language: go

go:
  - 1.x
  - 1.11.x
  - 1.12.x
  - 1.13.x

env:
  - GO111MODULE=on

install: true

script:
  - set -e
  - fmt=$(gofmt -l .)
  - test -z $fmt || (echo "please run gofmt" ; echo $fmt ; exit 1)
  - go run golang.org/x/lint/golint -set_exit_status $(go list ./...)
  - go test -race -vet=all ./...
  - go run github.com/fzipp/gocyclo -top 20 .
  - go run github.com/client9/misspell/cmd/misspell .
  - go run github.com/gordonklaus/ineffassign .